[colors]
# Specify the initial color of the lock screen.
init_color = 0x2e3440
# Specify the color of the lock screen after input is received.
input_color = 0x4c566a
# Specify the color of the lock screen on authentication failure.
fail_color = 0xbf616a
