#!/bin/sh

cd $(dirname $(readlink $0 || echo $0))

. ~/.config/nord/colors.sh

for m in $(bspc query --monitors); do
  bspc monitor "$m" --reset-desktops 1 2 3 4 5 6 7 8 9
done

bspc config normal_border_color  "${NORD1}"
bspc config active_border_color  "${NORD1}"
bspc config focused_border_color "${NORD4}"

bspc config window_gap   2
bspc config border_width 1

bspc config split_ratio 0.50

bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true

bspc config pointer_follows_monitor true

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc rule -a Screenkey manage=off

PANEL_WM_NAME='bspwm_panel'
if ! xdo id -a "${PANEL_WM_NAME}" > /dev/null; then
  ~/.config/lemonbar/panel.sh "${PANEL_WM_NAME}" &
fi
