XDG_CONFIG_HOME="${HOME}/.config"
XDG_DATA_HOME="${HOME}/.local/share"
XDG_CACHE_HOME="${HOME}/.cache"

if [ -z "${DISPLAY}${WAYLAND_DISPLAY}" ] && [ $(tty) = '/dev/tty1' ]; then
  exec dbus-run-session -- \
    env \
      XDG_SESSION_TYPE=wayland \
      XDG_CURRENT_DESKTOP=river \
      XKB_DEFAULT_LAYOUT="us,ru" \
      XKB_DEFAULT_OPTIONS="grp:alt_space_toggle" \
    river
fi
