#!/bin/zsh

unsetopt MAIL_WARNING       # Don't print a warning message if a mail file has been accessed.
setopt NOTIFY               # Report status of background jobs immediately.

setopt HIST_BEEP            # Beep when accessing non-existent history.
setopt HIST_FIND_NO_DUPS    # skip duplicate adjacent search results

setopt AUTO_CD              # Auto changes to a directory without typing cd.
setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt AUTO_NAME_DIRS

setopt INTERACTIVE_COMMENTS # support for comments in command line mode

export LANG=${LANG:-en_US.UTF-8}
export WORDCHARS='*?_-[]~;!#%^(){}<>'

command -v nvim &> /dev/null \
  && export EDITOR='nvim' \
  || export EDITOR='vim'
command -v code &> /dev/null \
  && export VEDITOR='code'
command -v less &> /dev/null \
  && export PAGER='less'

# Hitory
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=$HOME/.zsh_history
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY

# Async ZSH
export ZSH_AUTOSUGGEST_USE_ASYNC=true

export CASE_SENSITIVE=0
export CLICOLOR=1

_zcompinit_custom() {
  autoload -Uz compinit
  local zcd="${HOME}/.zcompdump"
  local zcdc="${zcd}.zwc"
  # Compile the completion dump to increase startup speed, if dump is newer or doesn't exist,
  # in the background as this is doesn't affect the current session
  if [[ -f "${zcd}"(#qN.m+1) ]]; then
        compinit -i -d "${zcd}"
        { rm -f "${zcdc}" && zcompile "${zcd}" } &!
  else
        compinit -C -d "${zcd}"
        { [[ ! -f "${zcdc}" || "${zcd}" -nt "${zcdc}" ]] && rm -f "${zcdc}" && zcompile "${zcd}" } &!
  fi
}

# borrowed from:
# https://www.reddit.com/r/zsh/comments/alkq5a/how_can_i_change_the_default_location_of_zshrc/egaw8q9
dotfiles="${${(%):-%x}:P:h:h}"
fpath+=("${dotfiles}/zsh/functions")
autoload -Uz ${dotfiles}/zsh/functions/*(.:t)

typeset -U config_files
config_files=(${dotfiles}/**/*.zsh)

unset dotfiles

# load the path files
for file in ${(M)config_files:#*/path.zsh}; do
  . "${file}"
done

# load antibody plugins
[ -f "${HOME}/.zsh_plugins.sh" ] && . "${HOME}/.zsh_plugins.sh"

# load everything but the path and completion files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}; do
  . "${file}"
done

# init completion
_zcompinit_custom

# load every completion after autocomplete loads
for file in ${(M)config_files:#*/completion.zsh}; do
  . "${file}"
done

unset config_files

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
[ -r "${HOME}/.localrc" ] && . "${HOME}/.localrc"

# remove duplicated from PATH
typeset -U PATH

# unbind vi mode
bindkey -r '^['
bindkey '\e[1;3D' backward-word
bindkey '\e[1;3C' forward-word

# start tmux if interactive
if [[ $- == *i* ]] && [ -z "${TMUX}" ] && command -v tmux 2>&1 > /dev/null; then
  tmux new-session -A -s main 
fi

