#!/bin/sh -e

TERMINAL_CMD=${TERMINAL_CMD:-${TERMINAL:-alacritty} -e}

DIRS=$(printf -- '%s/applications ' $(echo "${XDG_DATA_HOME:-${HOME}/.local/share}:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}" | tr ':' ' '))

# Based on https://github.com/Biont/sway-launcher-desktop
find -L ${DIRS} -type f -name '*.desktop' -printf '%p\0%P\n' 2>/dev/null \
  | sort -t '\0' -u -k 2 | cut -s -d '' -f1 \
  | xargs -I '{}' awk -v terminal_cmd="${TERMINAL_CMD}" '
    BEGIN{FS="="; action=-1}
    function hasValue(e, a){
      for (i in a)
        if (a[i]==e)
          return 1;
      return 0;
    }
    function expandExec(e){
      gsub(/%[[:alpha:]]/, "", e);
      if (terminal)
        e=sprintf("%s %s", terminal_cmd, e);
      if (path)
        e=sprintf("env -C %s %s", path, e);
      return sprintf("setsid -f %s", e);
    }
    /^#/{next}
    /^\[Desktop Entry\]$/{
      action=0;
    }
    action==0 && $1=="Type" && $2!="Application"{
      exit;
    }
    action==0 && $1=="Path" && NF==2{
      path=$2;
    }
    action==0 && $1=="Terminal" && $2=="true"{
      terminal=1;
    }
    action==0 && $1=="Actions" && NF==2{
      split($2,supported_actions,";");
    }
    /^\[Desktop Action \w+\]$/{
      action=-1;
      sub(/^\[Desktop Action /,"");
      sub(/\]$/,"");
      if (hasValue($0,supported_actions)) {
        action=1;
        ac++;
      } else {
        action=-1;
      }
    }
    $1=="Name" && NF==2{
      switch (action) {
      case 0:
        name=$2;
      case 1:
        actions[ac,"name"]=$2
      }
    }
    $1=="Exec"{
      sub(/^Exec=/, "");
      switch (action) {
      case 0:
        exec=$0;
      case 1:
        actions[ac,"exec"]=$0;
      }
    }
    $1=="NoDisplay" && $3=="true"{
      switch (action) {
      case 0:
        hidden=1;
      case 1:
        actions[ac,"hidden"]=1;
      }
    }
    END{
      if (!name || !exec || hidden)
        exit;
      printf("%s\n%s%c", expandExec(exec), name, 0);
      for (i=1; i<=ac; i++) {
        if (!actions[i,"exec"] || !actions[i,"name"] || actions[i,"hidden"])
          continue;
        printf("%s\n%s (%s)%c", expandExec(actions[i,"exec"]), name, actions[i,"name"], 0);
      }
    }' '{}'\
  | fzr --prompt='launch: '
