name: CI

on:
  create:
  push:
  pull_request:
    branches: [ master ]
  release:

jobs:
  Install:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 'voidlinux/voidlinux'
    steps:
      - name: 'Install dependencies'
        run: |
          xbps-install -Sy --yes \
            dash bash \
            curl \
            git \
            make \
            sudo

      - name: Checkout
        uses: actions/checkout@v3

      - name: Make
        run: make -Bk
